# Site settings
title: Developing Ninja
description: >
  The portfolio and blog of Wade Burelbach
baseurl: ''
url: http://developing.ninja
github:
  username: fafnirical
twitter:
  username: Fafnirical
social:
  name: Wade Burelbach
  links:
    - https://github.com/fafnirical
    - https://www.linkedin.com/in/wadeburelbach/
    - https://twitter.com/fafnirical
lang: en_US

# Analytics settings
webmaster_verifications:
  google: 9uLtc2_CWB-k8-mIFTsMRXhZNWuzmJj-n6z8xXGUsco
  bing: 07D0810BEEF8CA0A6349BCA1BBB25058
analytics:
  google: UA-51727784-1

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - .eslintrc.yaml
  - .gitignore
  - Gemfile*
  - package.json
  - node_modules/
  - README.md
  - yarn.lock
