# Site settings
title: Developing Ninja
email: wade.burelbach@gmail.com
description: >
  The portfolio and blog of Wade "Fafnirical" Burelbach
baseurl: ''
url: https://developing.ninja
twitter_username: fafnirical
github_username: fafnirical

# Analytics settings
analytics:
  google: UA-51727784-1

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - .eslintrc.yaml
  - .gitignore
  - Gemfile*
  - package.json
  - node_modules/
  - README.md
  - yarn.lock
